[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
experimental-string-processing = true

[tool.coverage.html]
directory = "docs/coverage"

[tool.coverage.run]
branch = true
omit = [
    "*/venv/*",
    "*/tests/*",
]

[tool.coverage.report]
fail_under = 90.00
show_missing = true

[tool.coverage.xml]
output = "docs/coverage/coverage.xml"

[tool.isort]
include_trailing_comma = true
profile = "black"
src_paths = "pysamplelib/"

[tool.mypy]
mypy_path = "./"
files = "."
exclude = "venv|__init__.py|tests|docs"

[tool.pytest.ini_options]
addopts = "-rA -v"
python_paths = "pysamplelib/"
testpaths = [
    "tests",
]
