[tool.black]
experimental-string-processing = true

[tool.isort]
include_trailing_comma = true
profile = "black"
src_paths = "python_library_template/"

[tool.pytest.ini_options]
addopts = "-rA -v"
python_paths = "python_library_template/"
testpaths = [
    "tests",
]
